modify: add deletedAt to group
gsainfoteam/groups-be pull request #48
Opened 2024-08-24 13:05 UTC by GanghyeonSeo

2024-08-24 13:11 UTC, siwonpada requested changes

2024-08-24 13:11 UTC, siwonpada commented on prisma/schema.prisma
> +  deletedAt     DateTime? @map("deleted_at")
이거 name Unique를 name + deleteAt 두게 합쳐서 Unique를 해야 할 것 같아요. -> 삭제된 그룹이랑 서로 이름이 같다고 그룹이 생성되지 않을 수 있기 때문입니다.

2024-08-26 17:14 UTC, siwonpada approved these changes

2024-08-26 17:15 UTC, siwonpada commented
name의 Unique가 없어지면서 버그가 나는 곳은 없는 거죠?

2024-08-27 11:31 UTC, GanghyeonSeo commented
> name의 Unique가 없어지면서 버그가 나는 곳은 없는 거죠?

넵 문제 없습니다.

2024-08-27 11:58 UTC, merged