53 sgh
gsainfoteam/groups-be pull request #55
Opened 2024-09-08 13:03 UTC by GanghyeonSeo

2024-09-08 13:22 UTC, siwonpada requested changes

2024-09-08 13:22 UTC, siwonpada commented on prisma/schema.prisma
> +  viewAs    ViewAs   @map("view_as") @default(Private)
이거 변수이름 visibility 어떤가요?
github에서 public/private할때 이 단어를 사용하고 있어서요.

2024-09-08 15:55 UTC, GanghyeonSeo commented on prisma/schema.prisma
> +  viewAs    ViewAs   @map("view_as") @default(Private)
반영하여 수정 완료했습니다.

2024-09-09 01:00 UTC, siwonpada commented on prisma/migrations/20240906075617_add_user_group_view_as/migration.sql
이 파일 삭제하고, migration dev 다시 해야할 것 같은데요.

2024-09-09 01:01 UTC, siwonpada commented on prisma/schema.prisma
> +  visibility  Visibility   @map("visibility") @default(Private)
이거 그룹의 visibility아닌가요?

2024-09-09 01:05 UTC, siwonpada commented on prisma/schema.prisma
> +  visibility  Visibility   @map("visibility") @default(Private)
아 그룹 내에서 인원이 보일지 숨을지 설정하는 거군요. 그러면 관련된 권한을 만들필요는 없을까요?

2024-09-09 02:11 UTC, GanghyeonSeo commented on prisma/schema.prisma
> +  visibility  Visibility   @map("visibility") @default(Private)
그룹 소속 여부 공개/비공개는 그냥 guard 기반으로 유저의 인증관련 검사를 하고, getUser 데코레이터를 바탕으로 어떤 유저인지 구분만 해서 유저가 스스로 변경하게 만들어도 괜찮지 않을까 생각했습니다. 제가 생각하지 못한 부분이 존재할 수도 있을 것 같기에, 관련된 아이디어가 있다면 말씀해주세요!

2024-09-09 02:12 UTC, GanghyeonSeo commented on prisma/migrations/20240906075617_add_user_group_view_as/migration.sql
넵 확인했습니다

2024-09-09 02:59 UTC, siwonpada commented on prisma/schema.prisma
> +  visibility  Visibility   @map("visibility") @default(Private)
그러면 그룹 소속의 공개/비공개는 해당 유저만 설정을 할 수 있는 거죠? 저는 한 유저가 다른 유저의 공개여부를 설정할 수 있는 상황이 있을 수도 있을 것이라고 생각해서 권한을 만들어야한다고 말한 것이었는데, 자신의 공개여부만 설정할 수 있다면 굳이 그럴 필요는 없을 것 같네요.

2024-09-11 01:31 UTC, siwonpada approved these changes

2024-09-11 06:58 UTC, merged